### PR TITLE
make the login work and fix some of the lint errors

### PR DESCRIPTION
**Pull request by elisha464**
I used the crunchyroll api to create a session and login with the provided credentials, and then I injected the session id to the default headers

### CODE REVIEW

**Comment by Godzil** [comment]
Hello, thanks for the push request, I can't accept it as is, as you change the coding style in my_request.ts, when I took the project it was completely inconsistant, I used my own, which is probably not the most commonly used in the JS world, but would try to keep this project consistant. 
As for the failing of Travis is due to lint issue, it is fine on that point, I will have a look at that.

Could you please make the coding style consistant with the rest of the project ( which is somewhat based on the Allman/BSD style: https://en.wikipedia.org/wiki/Indentation_style#Allman_style )

**Comment by Godzil** [comment]
By the way, do you think you could make the change in a way were we can easily switch from the old method to your proposal?
I would like to keep the old even with its clunky-ness in case CR break something in your way of login, so the user could use the old one if the new break.
May never happen, but just want to keep it as a failsafe.

**Comment by Godzil** [comment]
(And I've done a quick test, this seems to work fine, thanks!)
Will test it for a bit longer and will push an update after a couple of day of testing

**Comment by Jfigs101** [comment]
Are we able to update to this version yet? Also what's the command to
update this package?

**Comment by elisha464** [comment]
awesome, thanks for the merge, sorry about not doing the line breaks like you like them :P

**Comment by Godzil** [comment]
Seems to work reliably at the moment. I going to add another feature then will publish an update

**Comment by Godzil** [comment]
Oh and this fix #59 and #60

**Pull request merged**
